import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'


const font = Poppins({  
  weight: '700', 
  subsets: ['latin'] 
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  )
}
